# -*- coding: utf-8 -*-
"""Generate main_menu/setup/start/12_diplomacy.txt from the EU4 mod's history/diplomacy/.

The EU4 mod holds 120 relations in six files. The mapping onto EU5:

    EU4 vassal                              -> dependency subject_type = vassal
    EU4 dependency subject_type=tributary   -> dependency subject_type = tributary
    EU4 alliance (no trade_league flag)     -> scripted_mutual type = alliance

Not written here, deliberately:
  * the 13 alliances flagged `trade_league = 1` - EU5 has no trade league in diplomacy, they
    belong in 15_international_organizations.txt. See TODO.md.
  * the 2 `union` relations - EU5 has no union subject type; a union is an international
    organization (in_game/common/international_organizations/union.txt). See TODO.md.
  * history/diplomacy/hre.txt (emperor / celestial_emperor) - also an IO in EU5.

EU4 `end_date = 1821.1.1` is its own history-file end marker and has no EU5 equivalent, so it
is dropped. EU4 `start_date = 1444.1.1` is the EU4 start date; EU5's is 1337.4.1, so a start
date earlier than the game start would be needed for these to read as long-standing. Vanilla
only puts start_date on 28 of its 693 relations, so they are simply omitted.
"""
import os, re, csv, glob, collections

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(ROOT)
MOD = os.path.join(REPO, "wip mod folder")
SETUP = os.path.join(MOD, "main_menu", "setup", "start")
EU4 = r"C:\Users\timdo\OneDrive\Documents\Projects\Innea modding\Version 1.3 (1.33)\2226968141"
rd = lambda p: open(p, encoding='utf-8-sig', errors='replace').read()

remap = {r[0]: r[1] for r in list(csv.reader(open(os.path.join(ROOT, "tag_remap.csv"), encoding='utf-8')))[1:]}
c10 = rd(os.path.join(SETUP, "10_countries.txt"))
live = set(re.findall(r'^\t\t([A-Z][A-Z0-9]{2}) = \{', c10, re.M))
label = {m.group(1): m.group(2).split(',')[0].strip()
         for m in re.finditer(r'^\t\t([A-Z][A-Z0-9]{2}) = \{ # ([^\n]*)', c10, re.M)}
print("live EU5 tags: %d" % len(live))

rels = []
for f in sorted(glob.glob(os.path.join(EU4, "history", "diplomacy", "*.txt"))):
    for m in re.finditer(r'^(vassal|alliance|union|dependency)\s*=\s*\{(.*?)^\}', rd(f), re.S | re.M):
        b = m.group(2)
        g = lambda k: (re.search(k + r'\s*=\s*"?([A-Z0-9]{3})"?', b) or [None, None])[1]
        st = re.search(r'subject_type\s*=\s*"?([a-z_]+)"?', b)
        rels.append(dict(kind=m.group(1), first=g('first'), second=g('second'),
                         subject=st.group(1) if st else None,
                         league=bool(re.search(r'trade_league\s*=\s*1', b)),
                         src=os.path.basename(f)))
print("EU4 relations read: %d" % len(rels))

deps, allies, skipped = [], [], collections.Counter()
for r in rels:
    a, b = remap.get(r['first'], r['first']), remap.get(r['second'], r['second'])
    if a not in live or b not in live:
        skipped["tag not in 10_countries (%s->%s)" % (r['first'], r['second'])] += 1
        continue
    if r['kind'] == 'vassal':
        deps.append((a, b, 'vassal', r['src']))
    elif r['kind'] == 'dependency' and r['subject'] == 'tributary_state':
        deps.append((a, b, 'tributary', r['src']))
    elif r['kind'] == 'alliance' and not r['league']:
        allies.append((a, b, r['src']))
    elif r['kind'] == 'alliance' and r['league']:
        skipped["trade league -> international organization"] += 1
    elif r['kind'] == 'union':
        skipped["personal union -> international organization"] += 1
print("dependencies %d   alliances %d" % (len(deps), len(allies)))
for k, v in skipped.most_common():
    print("   not written: %-52s %d" % (k, v))

# group the dependencies under their overlord, biggest bloc first
by_over = collections.defaultdict(list)
for a, b, st, src in deps:
    by_over[a].append((b, st))

L = ["# Innea starting diplomacy, ported from the EU4 mod's history/diplomacy/.",
     "# Generated by map/gen_diplomacy.py.",
     "#",
     "# EU4 vassal -> subject_type = vassal;  EU4 tributary_state -> subject_type = tributary;",
     "# EU4 alliance -> scripted_mutual type = alliance.",
     "#",
     "# NOT here, and tracked in TODO.md: the 5 trade leagues and the 2 personal unions, both of",
     "# which are international organizations in EU5, not diplomatic relations.",
     "",
     "diplomacy_manager = {",
     ""]
for over in sorted(by_over, key=lambda t: (-len(by_over[t]), t)):
    subs = sorted(by_over[over])
    L.append("\t# %s - %d %s" % (label.get(over, over), len(subs),
                                 "subject" if len(subs) == 1 else "subjects"))
    for b, st in subs:
        L.append("\tdependency = { first = %s second = %-4s subject_type = %-10s } # %s" %
                 (over, b, st, label.get(b, b)))
    L.append("")
L.append("\t# alliances")
for a, b, src in sorted(allies):
    L.append("\tscripted_mutual = { first = %s second = %-4s type = alliance } # %s / %s" %
             (a, b, label.get(a, a), label.get(b, b)))
L += ["", "}", ""]
open(os.path.join(SETUP, "12_diplomacy.txt"), "w", encoding="utf-8", newline="\r\n").write("\n".join(L))
print("\nwritten %d lines to main_menu/setup/start/12_diplomacy.txt" % len(L))
